### ISSUE TITLE
Middy should be removed in order to 

### ISSUE THREAD

**Issue by Physicliar** [codetheworld-io/stripe-webhooks#1]
https://github.com/codetheworld-io/stripe-webhooks/blob/9edc5cb416418dfa1ff7402df4add63dc5df5fd8/src/functions/webhooks/handler.ts#L43

Middy should be removed in order to get body as raw string. This middleware automatically checks body and transform it into json

`export const main = webhooks`

**Comment by hoangsetup** [comment]
When we export `middyfy` at [`https://github.com/codetheworld-io/stripe-webhooks/blob/9edc5cb416418dfa1ff7402df4add63dc5df5fd8/src/libs/lambda.ts`](https://github.com/codetheworld-io/stripe-webhooks/blob/9edc5cb416418dfa1ff7402df4add63dc5df5fd8/src/libs/lambda.ts#L5)

```ts
export const middyfy = (handler) => {
  return middy(handler).use([
    injectLambdaContext(logger),
  ]);
};
```

We just registered one middleware - `injectLambdaContext`, and we removed `http-json-body-parser` from default template, then the `body` in the function is a raw body.
